import {Header} from "./components/header";
import {Main} from "./components/main";
import {Footer} from "./components/footer";
import {HTMLAttributes, ReactNode} from "react";
import {Metadata} from "next";


export interface ScmLayoutProps extends HTMLAttributes<HTMLDivElement> {
    children?: ReactNode
}

export const metadata: Metadata = {
    title: "Bunny SCM",
    description: "Generated by Ruiwen Zeng, zrwaus@gmail.com",
};

const ScmLayout = ({children}: ScmLayoutProps) => {
    return <div className="flex flex-col h-screen">
        <Header/>
        <Main>{children}</Main>

        <Footer/>
    </div>
};

export default ScmLayout;